### PR TITLE
Makefile.uk: Use -ffreestanding as internal build option

### PR DESCRIPTION
**Pull request by razvand**
As a standard C library (libc), newlib is to be built in a freestanding environment (i.e. not relying on a libc). For that, build internal newlib source code files with the `-ffreestanding` option. Otherwise, a hosted environment will be used; in a hosted environment, certain optimizations may be enabled by the compiler, and they may cause issues (such as an infinite set of calls).

### CODE REVIEW

**Review by marcrittinghaus — COMMENTED** [review]
Hey @razvand,

for improved maintainability, can you change to code to something like this?
```C
LIBNEWLIB_FLAGS		+= -ffreestanding
LIBNEWLIB_NO_BUILTINS	+= -D__NO_SYSCALLS__ -fno-builtin

LIBNEWLIBC_CFLAGS-y   += $(LIBNEWLIB_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS) $(LIBNEWLIB_NO_BUILTINS)
LIBNEWLIBM_CFLAGS-y   += $(LIBNEWLIB_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS) $(LIBNEWLIB_NO_BUILTINS)
LIBNEWLIBC_CXXFLAGS-y += $(LIBNEWLIB_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS) $(LIBNEWLIB_NO_BUILTINS)
LIBNEWLIBM_CXXFLAGS-y += $(LIBNEWLIB_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS) $(LIBNEWLIB_NO_BUILTINS)

LIBNEWLIBGLUE_SUPPRESS_FLAGS-y += -Wno-unused-parameter
LIBNEWLIBGLUE_CFLAGS-y   += $(LIBNEWLIBGLUE_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS)
LIBNEWLIBGLUE_CXXFLAGS-y += $(LIBNEWLIBGLUE_SUPPRESS_FLAGS-y) $(LIBNEWLIB_FLAGS)
```

**Comment by razvand** [comment]
> LIBNEWLIB_FLAGS += -ffreestanding

@marcrittinghaus , fixed, thanks for pointing it out.

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by eduardvintila — APPROVED** [review]
Looks good to me, as well. Thanks, @razvand!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by marcrittinghaus — APPROVED** [review]
Thanks @razvand!

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
